- Cargo.toml
- src/lib.rs
I tested this on a Raspberry Pi 2 with an SDD1306 OLED display and a Si7021 humidity/temperature sensor (driver crates will follow soon).
However, I'm not quite sure about the address parameter. The i2cdev crate will use the address when creating the LinuxI2CDevice, the embedded-hal traits expect the device address as parameter. I just ignore this parameter in this implementation. Is this the right way to do it?
> embedded-hal i2c traits implementation using i2cdev

- Cargo.toml
- src/lib.rs
Do we have opinions on the use of `unproven` traits in this library?
> Added input pin impl (requires unproven hal trait)

- CHANGELOG.md
- Cargo.toml
Since #9 still seems to be WIP a small update for crates.io would be nice, so I could move back to the crates.io version of this package.
> Release new Patch on crates.io with InputPin Support

- Cargo.toml
rust-i2cdev has a new minor version that removes a pile of dependencies (and speeds up builds measurably), see: https://github.com/rust-embedded/rust-i2cdev/pull/47
This PR bumps i2cdev to the updated version and adds a missing newline to the end of cargo.toml
> Bump i2cdev version

- CHANGELOG.md
- Cargo.toml
Following #14 this release contains a newer version of the i2cdev crate that decreases the number of dependencies and thus build time (measured on an rpi3 from 1hr 20 mins to 20 mins).
> Release new patch on crates.io with minimised i2c dependencies

- src/lib.rs
The library currently does not currently build anymore, because upstream libraries have added new deprecation warnings. A deprecation warning should not break compilation though. There was a post on Reddit about this about a year ago, but I can't find it anymore.
I think adding a CI check step would be fine, but `#[deny(warnings)]` is a bit too much.
These are the warnings:
```
warning: use of deprecated item 'hal::digital::OutputPin': Deprecated because the methods cannot return errors. Users should use the traits in digital::v2.
--> src/lib.rs:111:6                                                       
|                                                                         
111 | impl hal::digital::OutputPin for Pin {                                  
|      ^^^^^^^^^^^^^^^^^^^^^^^ …
```
> Remove #[deny(warnings)]

- src/lib.rs
The v1 traits are deprecated because they don't have a way to report errors.
Gets rid of the deprecation warnings (which are hard errors until #17 is merged).
> Move to digital v2 traits

- Cargo.toml
Currently dependencies have to be compiled multiple times due to version mismatches. Upgrading to `spidev=0.4` fixes that problem.
Before:
```
├── linux-embedded-hal v0.2.2
│   ├── cast v0.2.2
│   ├── embedded-hal v0.2.3 (*)
│   ├── i2cdev v0.4.2
│   │   ├── bitflags v1.1.0
│   │   ├── byteorder v1.3.2
│   │   ├── libc v0.2.62
│   │   └── nix v0.14.1
│   │       ├── bitflags v1.1.0 (*)
│   │       ├── cfg-if v0.1.9
│   │       ├── libc v0.2.62 (*)
│   │       └── void v1.0.2 (*)
│   ├── spidev v0.3.0
│   │   ├── bitflags v0.3.3
│   │   ├── libc v0.2.62 (*)
│   │   └── nix v0.6.0
│   │       ├── bitflags v0.4.0
│   │       ├── cfg-if v0.1.9 (*)
│   │       ├── libc v0.2.62 (*)
│   │       └── void v1.0.2 (*)
│   │       [build-dependencies]
│   │       ├── rustc_version v0.1.7
│   │ …
```
> Update spidev dependencies

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
This fixes #25 by implementing a transactional write-read without STOP in the middle.
It also fixes a type cast which was the only warning present.
> Transactional WriteRead

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
I updated the changelog with everything that happened since the 0.2.2 release and bumped the minor version because of the digital::v2.
I also fixed setting the embedded-hal version to 0.2.3 because that is when the digital::v2 traits were released.
This branch sits on top of #26 with the hopeful date of today :)
> Release 0.3.0 preparation

- CHANGELOG.md
- Cargo.toml
- src/cdev_pin.rs
- src/lib.rs
- src/sysfs_pin.rs
- added both features by default
- re-export `Pin` type using type aliases
- default behaviour exports cdev for backwards compatibility
- package builds with any combination of gpio features
> Updated logic around sysfs/cdev pin selection

- src/lib.rs
There were two links in the doc comments (of the `Spidev` struct and the `Spidev::open()` method) that guided to the documentation of the old (0.3.0) version of the spidev crate. This patch updates those links to direct to the new version (0.4.0, the same as _this_ crate depends on).
> Update the spidev documentation links

- Cargo.toml
- src/lib.rs
- src/timer.rs
Based on the [implementation by @MathiasKoch](https://github.com/BlackbirdHQ/ublox-cellular-rs/blob/master/examples/common/timer.rs).
> Add timer::CountDown implementation

- CHANGELOG.md
- Cargo.toml
- src/cdev_pin.rs
- src/lib.rs
- src/serial.rs
- src/sysfs_pin.rs
- src/timer.rs
Builds on and superseeds #43 and #48.
> Embedded hal 1.0.0 alpha.3

- Cargo.toml
- src/cdev_pin.rs
- src/lib.rs
- src/serial.rs
- src/sysfs_pin.rs
- src/timer.rs
I adapted this to the `embedded-hal-1.0.0-alpha.1` release.
As part of it I also replaced `void` with `core::convert::Infallible`.
(blocked on https://github.com/rust-embedded/embedded-hal/issues/177)
> Adapt to embedded-hal-1.0.0-alpha.1

- Cargo.toml
- examples/transactional-i2c.rs
- src/lib.rs
I implemented the transactional I2C interface from https://github.com/rust-embedded/embedded-hal/pull/223 and added an example with a driver which does a combined Write/Read transaction.
This is based on previous work from #33 by @ryankurte, https://github.com/rust-embedded/rust-i2cdev/pull/51 and is similar to #35.
> Implement transactional I2C interface and add example

- Cargo.toml
- src/cdev_pin.rs
- src/lib.rs
- src/serial.rs
- src/sysfs_pin.rs
- src/timer.rs
Implementation of transactional SPI
- replaces https://github.com/rust-embedded/linux-embedded-hal/pull/33
- blocked on:
- ~https://github.com/rust-embedded/embedded-hal/pull/191~
- ~https://github.com/rust-embedded/linux-embedded-hal/pull/34~
~Important: remove patch and bump hal version before merging~
> Add transactional SPI

- .github/bors.toml
- .github/workflows/ci.yml
- Cargo.toml
It'd be lovely to allow streaming of chip line events asynchronously now that `gpio-cdev` supports it.
> Update gpio-cdev to 0.4.0 and add async-tokio feature

- CHANGELOG.md
> Note the change to the MSRV in the changelog

- CHANGELOG.md
- src/cdev_pin.rs
- src/sysfs_pin.rs
When an output pin is in active-low mode, the try_set_low and try_set_high functions currently incorrect behavior.
In keeping with the input behavior for `try_is_high` and `try_is_low`, "high" and "low" should refer to the actual output voltage. This works as expected for pins that are not in active-low mode, but if a pin is in active-low mode, then the opposite happens:
* calling `try_set_low` sets the voltage high
* calling `try_set_high` sets the voltage low
This bug and the fix have been verified using [this test program](https://github.com/MorganR/active-low-test).
> Fix active low behavior of GPIO output pins

- .github/bors.toml
- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- examples/transactional-i2c.rs
- src/cdev_pin.rs
- src/delay.rs
- src/i2c.rs
- src/lib.rs
- src/serial.rs
- src/spi.rs
- src/sysfs_pin.rs
- src/timer.rs
I will add support for embedded-hal 0.2.x in parallel as described [here](https://github.com/rust-embedded/embedded-hal#adding-support-for-an-embedded-hal--alpha-version-in-a-hal-implementation). This PR contains some preparation for that.
> Update embedded-hal to version 1.0.0-alpha.5

- Cargo.toml
Doing this for 0.3.x is not possible due to a raise in the MSRV.
Closes #70
> Raise minimum dependency versions to enforce using a newer nix

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
Adds the features `i2c` and `spi` for an optional dependency on `i2cdev` and `spidev`.
Discussion in #80.
Closes #80
> Add features for spi and i2c

- CHANGELOG.md
- Cargo.toml
Now that #83 is in, it would be good to publish a new alpha release.
> Prepare 0.4.0-alpha.3 release

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/serial.rs
Replace the unmaintained serial-rs crate with serialport-rs.
Closes #86
> serial: Replace the serial-rs crate with serialport-rs

- .github/bors.toml
- .github/workflows/ci.yml
- .github/workflows/clippy.yml
- .github/workflows/rustfmt.yml
- src/serial.rs
- src/spi.rs
> Switch to GHMQ

- CHANGELOG.md
- src/spi.rs
I think this should be OK but so far I've only tested it on equal-sized buffers and reads-bigger-than-writes as I don't have anything convenient set up for checking what happens with writes-bigger-than-reads.
> Fix #97: split unbalanced SPI transfers into rw+r or rw+w

- CHANGELOG.md
- Cargo.toml
- src/i2c.rs
- src/serial.rs
I thought the crate could be bumped to 1.0.0-rc.1 as well. What do you think?
> Update embedded-hal to 1.0.0-rc.1

- CHANGELOG.md
- src/lib.rs
- src/spi.rs
As discussed in #99, split `Spidev` into `SpidevDevice` and `SpidevBus`, each implementing the respective embedded-hal trait.
Compared to the original plan, it seems easier to just let the CS pin be driven normally, and say users can configure SPI_NO_CS if required. I couldn't spot any good way for us to _change_ the configuration to just set this flag without overriding whatever existing mode configuration the user had, and since it should always be a dummy pin anyway, it shouldn't usually matter if it gets toggled.
In the end therefore there's no change to the implementations, just splitting which struct each trait is implemented for (and duplicating the various helper impls).
> Split Spidev into device and bus structs

- .github/workflows/ci.yml
- .github/workflows/clippy.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- src/cdev_pin.rs
TODO: update branch protection rules to require 1.65.0
Fixes #103
> Prepare `-alpha.4` release

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- I am working on some [examples](https://openbeagle.org/ayush1325/vsx-examples) for [PocketBeagle 2](https://www.beagleboard.org/boards/pocketbeagle-2), and we have decided to use Rust for it.
- Since it is a constrained device, it would be best to have minimal dependencies. To that end, I will be disabling `default-features` in most single peripheral examples.
- However, currently some dependencies are pulled even with the default features disabled, so I would prefer it if they were also behind a selectable feature instead.
> Make unused dependencies optional
